---
# yaml-language-server: $schema=https://json.schemastore.org/taskfile.json
version: 3

tasks:
  up:
    desc: "run docker compose up for a single service."
    cmds:
      - docker-compose -f {{ .COMPOSE_FILE }} up -d {{ .SERVICE_NAME }}
    vars:
      COMPOSE_FILE: '{{ default "docker-compose.yml" .COMPOSE_FILE }}'
      SERVICE_NAME: '{{ .SERVICE_NAME }}'
  
  down:
    desc: "run docker compose up for a single service."
    cmds:
      - docker-compose -f {{ .COMPOSE_FILE }} down {{ .SERVICE_NAME }}
    vars:
      COMPOSE_FILE: '{{ default "docker-compose.yml" .COMPOSE_FILE }}'
      SERVICE_NAME: '{{ .SERVICE_NAME }}'

  restart:
    desc: "run docker compose restart for a single service."
    cmds:
      - docker-compose -f {{ .COMPOSE_FILE }} restart {{ .SERVICE_NAME }}
    vars:
      COMPOSE_FILE: '{{ default "docker-compose.yml" .COMPOSE_FILE }}'
      SERVICE_NAME: '{{ .SERVICE_NAME }}'
