---
# yaml-language-server: $schema=https://json.schemastore.org/taskfile.json
version: 3

tasks:
  install:
    desc: "Installs swagger binary."
    status:
      - which swagger
    cmds:
      - go install github.com/go-swagger/go-swagger/cmd/swagger@latest
      - ln -s ~/go/bin/swagger /usr/local/bin/swagger
