version: '3'
services:
  db:
    platform: linux/x86_64
    image: mysql:8
    container_name: sample_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: sample_db
    ports:
      - "8086:3306"

  pubsub:
    image: google/cloud-sdk
    container_name: sample_pubsub
    command: gcloud beta emulators pubsub start --quiet --host-port=0.0.0.0:8085
    environment:
      - PUBSUB_PROJECT_ID=sample-go-app
    ports:
      - "8085:8085"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  grafana:
    image: grafana/grafana-enterprise
    container_name: sample_grafana
    ports:
      - "3000:3000"
    volumes:
      - "./tmp/grafana:/var/lib/grafana"
    depends_on:
      prometheus:
        condition: service_started
      jaeger:
        condition: service_started

  prometheus:
    image: prom/prometheus
    container_name: sample_prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./build/prometheus:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      sample:
        condition: service_started
    links:
      - sample

  jaeger:
    image: jaegertracing/all-in-one
    container_name: sample_jaeger
    ports:
      - "16686:16686"
      - "4318:4318"
    environment:
      - COLLECTOR_OTLP_ENABLED=true

  sample:
    build:
      context: ./build/sample
      dockerfile: Dockerfile
    container_name: sample_app
    ports:
      - "8080:8080"
    volumes:
      - ./:/app
    links:
      - db
      - jaeger
    depends_on:
      db:
        condition: service_started
      pubsub:
        condition: service_started
      jaeger:
        condition: service_started
