version: '3'
services:
  db:
    platform: linux/x86_64
    image: mysql:8
    container_name: sample_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: sample_db
    ports:
      - "8086:3306"

  pubsub:
    image: google/cloud-sdk
    container_name: sample_pubsub
    command: gcloud beta emulators pubsub start --quiet --host-port=0.0.0.0:8085
    environment:
      - PUBSUB_PROJECT_ID=sample-go-app
    ports:
      - "8085:8085"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  grafana:
    image: grafana/grafana-enterprise
    container_name: sample_grafana
    ports:
      - "3000:3000"
    volumes:
      - "./tmp/grafana:/var/lib/grafana"

  prometheus:
    image: prom/prometheus
    container_name: sample_prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./build/prometheus:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    extra_hosts:
      - "host.docker.internal:host-gateway"
