---
# yaml-language-server: $schema=https://json.schemastore.org/taskfile.json
version: 3

includes:
  sample: ./tasks/sample.yml
  activity: ./tasks/activity.yml
  message: ./tasks/message.yml
  traefik: ./tasks/service/traefik.yml
  go: ./tasks/helper/golang.yml

vars:
  SAMPLE_APP_DIR: ./cmd/sample
  ACTIVITY_APP_DIR: ./cmd/activity
  PKG_DIR: ./pkg

tasks:
  setup-deps:
    desc: Setup the basic dependencies to run the application.
    cmds:
      - task: sample:setup-deps
      - task: message:setup-deps
      - task: activity:setup-deps

  init:
    desc: Initialize the development environment
    cmds:
      - task: sample:init
      - task: message:init

  run:tests:
    desc: Test all the applications.
    cmds:
      - task: go:test
        vars:
          GO_PROJECT_FOLDER: '{{ .PKG_DIR }}'
      - task: sample:run-tests

  all:up:
    desc: Start the applications with traefik API Gateway
    cmds:
      - task: sample:start
      - task: traefik:up

  all:down:
    desc: Start the applications with traefik API Gateway
    cmds:
      - task: traefik:down
      - task: sample:down
      - task: activity:down
      - task: sample:grafana:down
      - task: sample:prometheus:down
      - task: sample:jaeger:down

  go-checks:
    desc: "To run all the code checks for the sample application."
    cmds:
      - task: go:vet
        vars:
          GO_PROJECT_FOLDER: '{{ .SAMPLE_APP_DIR }}'
      - task: go:lint
        vars:
          GO_PROJECT_FOLDER: '{{ .SAMPLE_APP_DIR }}'
      - task: go:vet
        vars:
          GO_PROJECT_FOLDER: '{{ .ACTIVITY_APP_DIR }}'
      - task: go:lint
        vars:
          GO_PROJECT_FOLDER: '{{ .ACTIVITY_APP_DIR }}'
      - task: go:vet
        vars:
          GO_PROJECT_FOLDER: '{{ .PKG_DIR }}'
      - task: go:lint
        vars:
          GO_PROJECT_FOLDER: '{{ .PKG_DIR }}'
