---
# yaml-language-server: $schema=https://json.schemastore.org/taskfile.json
version: 3

includes:
  sample: ./tasks/sample.yml
  message: ./tasks/message.yml
  traefik: ./tasks/service/traefik.yml

tasks:
  setup-deps:
    desc: Setup the basic dependencies to run the application.
    cmds:
      - task: message:setup-deps

  init:
    desc: Initialize the development environment
    cmds:
      - task: sample:init
      - task: message:init

  all:up:
    desc: Start the applications with traefik API Gateway
    cmds:
      - task: sample:start
      - task: traefik:up

  all:down:
    desc: Start the applications with traefik API Gateway
    cmds:
      - task: traefik:down
      - task: sample:down
