---
# yaml-language-server: $schema=https://json.schemastore.org/taskfile.json
version: 3

includes:
  docker: ./docker.yml

tasks:
  start:
    cmds:
      - task: docker:compose-up-single
        vars:
          SERVICE_NAME: grafana

  stop:
    cmds:
      - task: docker:compose-down-single
        vars:
          SERVICE_NAME: grafana
