---
# yaml-language-server: $schema=https://json.schemastore.org/taskfile.json
version: 3

includes:
  docker: ./docker.yml

tasks:
  up:
    cmds:
      - task: docker:compose-up-single
        vars:
          SERVICE_NAME: grafana

  down:
    cmds:
      - task: docker:compose-down-single
        vars:
          SERVICE_NAME: grafana

  restart:
    cmds:
      - task: down
      - task: up
