---
# yaml-language-server: $schema=https://json.schemastore.org/taskfile.json
version: 3

includes:
  docker: ./helper/docker.yml
  pubsub: ./service/pubsub.yml

tasks:
  setup-deps:
    desc: Setup the basic dependencies to run the application.
    status:
      - command -v protoc
    cmds:
      - go install google.golang.org/protobuf/cmd/protoc-gen-go@latest

  init:
    desc: "Setup the environment variables."
    cmds:
      - cp .env.sample .env
      - protoc -I={{.SRC_DIR}} --go_out={{.DST_DIR}} {{.SRC_DIR}}/message.proto
    vars:
      SRC_DIR: '../../api/message'
      DST_DIR: './'
    dir: ./cmd/message

  read:
    desc: "read the message in the message."
    dotenv: ['.env']
    cmds:
      - go run main.go read
    dir: ./cmd/message

  up:
    desc: "Start the message service."
    dotenv: ['.env']
    cmds:
      - task: pubsub:up
      - task: read
    dir: ./cmd/message

  down:
    desc: "Start the message service."
    dotenv: ['.env']
    cmds:
      - task: pubsub:down
    dir: ./cmd/message

  publish:
    desc: "Publish the message in the message."
    dotenv: ['.env']
    cmds:
      - go run main.go publish
    dir: ./cmd/message
