---
# yaml-language-server: $schema=https://json.schemastore.org/taskfile.json
version: 3

includes:
  docker: ./helper/docker.yml
  prometheus: ./service/prometheus.yml
  jaeger: ./service/jaeger.yml
  grafana: ./service/grafana.yml
  db: ./service/db.yml

tasks:
  init:
    desc: "Setup the environment variables."
    status:
      - test -f .env
    cmds:
      - cp .env.sample .env
    dir: ./cmd/sample

  migrate:
    desc: "Migrate the sample application's database."
    deps:
      - task: db:up
    cmds:
      - task: docker:up
        vars:
          SERVICE_NAME: sample_migrator

  up:
    desc: "Start the sample application."
    cmds:
      - task: docker:up
        vars:
          SERVICE_NAME: sample

  down:
    desc: "Stop the sample application."
    cmds:
      - task: docker:down
        vars:
          SERVICE_NAME: sample

  restart:
    desc: "Restart the sample application."
    cmds:
      - task: docker:restart
        vars:
          SERVICE_NAME: sample
  
  run-local:
    desc: "Start the sample application locally. For docker internals only."
    dotenv: [.env]
    cmds:
      - go run main.go
    dir: ./cmd/sample

  start:
    desc: "Start the sample application and its dependent services."
    dotenv: ['.env']
    cmds:
      - task: db:up
      - task: jaeger:up
      - task: grafana:up
      - task: up
      - task: prometheus:up
    dir: ./cmd/sample

  stop:
    desc: "Stop the sample application and its dependent services."
    dotenv: ['.env']
    cmds:
      - task: down
      - task: db:down
      - task: grafana:down
      - task: prometheus:down
      - task: jaeger:down
    dir: ./cmd/sample
