---
# yaml-language-server: $schema=https://json.schemastore.org/taskfile.json
version: 3

includes:
  docker: ./docker.yml

tasks:
  init:
    desc: "Setup the environment variables."
    status:
      - test -f .env
    cmds:
      - cp .env.sample .env
    dir: ././services/sample

  db-up:
    cmds:
      - task: docker:compose-up-single
        vars:
          SERVICE_NAME: db

  db-down:
    cmds:
      - task: docker:compose-down-single
        vars:
          SERVICE_NAME: db

  run:
    desc: "Start the sample application."
    dotenv: ['.env']
    cmds:
      - go run main.go
    dir: ././services/sample
