pubsub:
  name: sample-pubsub
  project: sample-go-app
  topic: sample-topic
  subscription: sample-subscription
mysql:
  name: sample_db
  user: user
  password: password
  host: sample_db
  port: 8086
launch_darkly:
  secret_key: some-secret-key
jaeger:
  host: "sample_jaeger:4318"
  path: "/v1/traces"
