mysql:
  name: sample_db
  user: root
  password: root
  host: localhost
  port: 8086
launch_darkly:
  secret_key: some-secret-key
activity:
  host: somehost
  port: 8080
jaeger:
  host: "no-matter"
  path: "no-matter"
